# Liiklus config defaults
storage:
  positions:
    type: DYNAMODB

  records:
    type: KAFKA


# Spring Boot config
spring:
  jmx:
    enabled: false

  cache:
    type: NONE

endpoints:
  prometheus:
    sensitive: false

server.port: -1

armeria:
  ports:
    - port: ${armeria.port:8080}
      protocol: HTTP
  graceful-shutdown-quiet-period-millis: 100
  graceful-shutdown-timeout-millis: 200