# Liiklus config defaults
storage:
  positions:
    type: DYNAMODB

  records:
    type: KAFKA

kafka:
  bootstrapServers: # Required

dynamodb:
  positionsTable: # Required

grpc:
  port: 6565

plugins:
  dir: ./plugins
  pathMatcher: "*.jar"